# Generated by Django 5.1.1 on 2024-11-27 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition', models.CharField(max_length=100)),
                ('match_between', models.CharField(max_length=100)),
                ('versus', models.CharField(max_length=100)),
                ('toss_won_by', models.CharField(max_length=100)),
                ('elected_to', models.CharField(choices=[('Batting', 'Batting'), ('Bowling', 'Bowling')], max_length=10)),
                ('overs', models.IntegerField()),
                ('pitch_type', models.CharField(max_length=10)),
                ('ball_type', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('team1_score', models.IntegerField()),
                ('team1_wickets', models.IntegerField()),
                ('team2_score', models.IntegerField()),
                ('team2_wickets', models.IntegerField()),
                ('scorer_name', models.CharField(max_length=100)),
                ('losing_captain', models.CharField(max_length=100)),
                ('umpires', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InningsBowler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('innings', models.IntegerField(choices=[(1, 'First'), (2, 'Second')])),
                ('name', models.CharField(max_length=100)),
                ('overs', models.FloatField()),
                ('maidens', models.IntegerField()),
                ('runs_given', models.IntegerField()),
                ('wickets', models.IntegerField()),
                ('wides', models.IntegerField()),
                ('no_balls', models.IntegerField()),
                ('economy', models.FloatField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bowlers', to='match.match')),
            ],
        ),
        migrations.CreateModel(
            name='InningsBatsman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('innings', models.IntegerField(choices=[(1, 'First'), (2, 'Second')])),
                ('name', models.CharField(max_length=100)),
                ('runs', models.IntegerField()),
                ('balls_faced', models.IntegerField()),
                ('fours', models.IntegerField()),
                ('sixes', models.IntegerField()),
                ('strike_rate', models.FloatField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batsmen', to='match.match')),
            ],
        ),
    ]
