# Generated by Django 5.1.1 on 2024-11-27 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inningsbowler',
            name='match',
        ),
        migrations.RemoveField(
            model_name='match',
            name='scorer_name',
        ),
        migrations.AddField(
            model_name='match',
            name='scorer_signature',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='match',
            name='ball_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='match',
            name='elected_to',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='match',
            name='losing_captain',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='match',
            name='pitch_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='match',
            name='team1_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='team1_wickets',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='team2_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='team2_wickets',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='umpires',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='Batsman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('innings', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('runs', models.IntegerField(default=0)),
                ('balls_faced', models.IntegerField(default=0)),
                ('fours', models.IntegerField(default=0)),
                ('sixes', models.IntegerField(default=0)),
                ('strike_rate', models.FloatField(default=0.0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.match')),
            ],
        ),
        migrations.CreateModel(
            name='Bowler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('innings', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('overs', models.FloatField(default=0.0)),
                ('maidens', models.IntegerField(default=0)),
                ('runs_given', models.IntegerField(default=0)),
                ('wickets', models.IntegerField(default=0)),
                ('wides', models.IntegerField(default=0)),
                ('no_balls', models.IntegerField(default=0)),
                ('economy', models.FloatField(default=0.0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.match')),
            ],
        ),
        migrations.CreateModel(
            name='FallOfWicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('innings', models.IntegerField()),
                ('wicket_number', models.IntegerField()),
                ('score_at_wicket', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.match')),
            ],
        ),
        migrations.DeleteModel(
            name='InningsBatsman',
        ),
        migrations.DeleteModel(
            name='InningsBowler',
        ),
    ]
